### ISSUE TITLE
positon "below" subtract SD

### ISSUE THREAD

**Issue by dauntaun** [leonardblaschek/tukeygrps#1]
print_position = "below" should subtract rather than add the standard deviation as the lettering appears above the minimum values by default (negative numbers for print_adjust).

**Comment by dauntaun** [comment]
Suggestion to simplify the print_position code: 

HSD.test already provides the means, sd, min, max and quartiles through .$means. The main function could return those along with the letters in separate columns, then you could simply specify what you want as y in geom_text.

**Comment by leonardblaschek** [comment]
Good point, we should implement a conditional default value for print_adjust depending on print_position. But I think we should leave the operator as an addition, so that the adjustment remains intuitive (positive print_adjust is upwards adjustment, negative print_adjust is downward adjustment)

Concerning the other idea, I would like to limit as much as the input to the letter_groups function and away from the geom_text implementation, and I also think its good to keep identical aesthetics for plotting and annotation geoms. But you could change the function so that it takes the mean/min/max directly from the groups object instead of calculating them anew.

Feel free to change it and make a pull request, I probably won't get to change it myself in the next couple weeks.
